import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "next-themes";
import Header from "@/Components/Structure/Header/Header";
import Footer from "@/Components/Structure/Footer/Footer";
import MouseBorder from "@/Components/Structure/Mouse";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: {
    default: "DevoWeb",
    template: "%s | DevoWeb",
  },
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${inter.className}`}>
        <ThemeProvider attribute="class" enableSystem defaultTheme="system">
          <div className="flex min-h-screen flex-col justify-between bg-[var(--secondary-color)] transition-all duration-300">
            <MouseBorder />
            <div>
              <header className="mx-4">
                <Header />
              </header>
              <main>{children}</main>
            </div>
            <footer>
              <Footer />
            </footer>
          </div>
        </ThemeProvider>
      </body>
    </html>
  );
}
